e:
  image: byteflair/elastic-marvel
  command: elasticsearch
  ports:
   - "9200:9200"
l:
  image: logstash:latest
  command: logstash -f /config-dir/logstash.conf
  volumes:
   - ./logstash:/config-dir
  links:
   - e:elasticsearch
  ports:
   - "5000:5000/udp"
   - "5000:5000"
k:
  image: byteflair/kibana-marvel
  links:
   - e:elasticsearch
  ports:
   - "5601:5601"
